// version-I/src/pages/home/InputForm.svelte
<script>
  import { onDestroy } from "svelte";
  import { inputFormStore } from "../../common/inputForm-store";
  import SWInput from "./SWInput.svelte";
  import SWButton from "./SWButton.svelte";
  import ResultButton from "./ResultButton.svelte";

  let inputs;
  let buttons;
  const unsubscribe = inputFormStore.subscribe(inputForm => {
    inputs = inputForm.filter(item => item.visible).map(item => item.resourceKey);
    buttons = inputForm.filter(item => !item.mandatory).map(item => item.resourceKey);
  });

  onDestroy(() => {
    if (unsubscribe) {
      unsubscribe();
    }
  });
</script>


<div class="flex w-full flex-col">
  {#each inputs as input}
    <SWInput resourceKey={input} />
  {/each}
  <div class="flex w-full justify-between">
    {#each buttons as button}
      <SWButton resourceKey={button} />
    {/each}
  </div>
  <div class="flex justify-center my-8">
    <ResultButton />
  </div>
</div>

// version-H/components/InputForm.tsx
import React, { FC } from "react";
import {StarWarsSearch} from '@/components/StarWarsSearch';
import {Button} from '@/components/Button';
import {Resources} from '@/common/types';

type InputFormProps = {
  resources: Resources;
};

export const InputForm: FC<InputFormProps> = ({ resources }) => {
  const mandatory = Object.values(resources).filter(r => r.mandatory);
  const optional = Object.values(resources).filter(r => !r.mandatory);
  return (
    <div className="w-full">
      {mandatory.map(r => <StarWarsSearch key={`field-${r.singular}`} label={r.label ? r.label : r.singular} />)}
      <div className="flex justify-between my-4">
        {optional.map(r => <Button key={`button-${r.singular}`} name={`Add ${r.singular}`} /> )}
      </div>
      <div className="flex justify-center">
        <Button name={'Generate Plot'} />
      </div>
    </div>
  );
};
