// version-G/src/components/pages/ResultPage.vue
<template>
  <div class="row">
    <div class="col-md-12">
      <h2>{{getPlot().title}}</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <p class="plot-text" v-html="getPlot().description">
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h3>Used resources</h3>
      <ul class="used-resources">
        <li v-for="resource in getUsedResources()" v-bind:key="resource.name">
          <a v-bind:href="resource.url">{{resource.url}}</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <button
        type="button"
        class="btn btn-primary btn-lg"
        v-on:click="onClick()"
      >
        Generate New Plot
      </button>
    </div>
  </div>
</template>

<script>
import { defineComponent } from 'vue';
import { useStore } from 'vuex'
import { useRouter } from 'vue-router'
import { key } from "@/store/store";
import { generatePlot } from "@/utils/plotGenerator";

export default defineComponent({
  name: 'ResultPage',

  data() {
    const store = useStore(key);
    const router = useRouter()

    function getPlot() {
      const selected = store.getters.getSelectedSuggestions;
      return generatePlot(...(selected.map(i => i.value.name)));
    }
    function getUsedResources() {
      return store.getters.getSelectedSuggestions.map(s => s.value);
    }
    function onClick() {
      // if returning from the /result page, reset selected values to start from the beginning
      store.dispatch("resetSelected");
      store.dispatch("hideOptionalInputs");
      router.push('home');
    }

    return {
      getPlot,
      getUsedResources,
      onClick,
    };
  }
})
</script>

<style scoped>
.used-resources {
  font-family: 'Comic Sans, Comic Sans MS, cursive;', serif;
  font-size: larger;
  list-style: none;
}

.plot-text {
  font-size: large;
  font-family: 'Comic Sans, Comic Sans MS, cursive;', serif;
  color: yellow;
  background: black;
  text-align: justify;
  padding: 10px;
}

.highlight-word {
  color: orangered;
}
</style>

// version-B/src/pages/result/ResultPage.tsx
import * as React from 'react';
import { Col, Form, FormGroup, Button, Container } from 'reactstrap';
import { generatePlot } from "./plotGenerator";
import dompurify from 'dompurify';
import { Redirect } from "react-router-dom";

class GenerateNewPlotBnt extends React.Component<any,any> {

    render() {

        const {generateNewPlot} = this.props;

        return (
            <Col>
                <div className="text-center result-space">
                    <Button color="primary" size="lg" onClick={e => generateNewPlot()}>Generate New Plot</Button>
                </div>
            </Col>
        );
    }
}

const Description = (props) => {
    const
        sanitizer = dompurify.sanitize,
        sanitizedMarkup = sanitizer(props.description),
        markup = {__html: sanitizedMarkup};
    return (
        <Col>
            <div className="text-center result-space">
                <p className="plot-text">
                    <span dangerouslySetInnerHTML={markup}/>
                </p>
            </div>
        </Col>
    );
};

const Title = (props) => {
    return (
        <Col>
            <div className="text-center result-space">
                <h2>{props.title}</h2>
            </div>
        </Col>
    );
};

const ResourceLink = (props) => {
    return (
        <li key={props}>
            <a href={props.url}>{props.url}</a>
        </li>
    );
};

const Resources = (props) => {
    return (
        <Col>
            <div className="text-center result-space">
                <h3>Used resources</h3>
                <ul className="used-resources">
                    {props.resources.map((url, idx) => <ResourceLink key={idx} url={url}/>)}
                </ul>
            </div>
        </Col>
    );
};

class Plot extends React.Component<any, any> {

    constructor(props) {
        super(props);
        this.generateNewPlot = this.generateNewPlot.bind(this);
    }

    generateNewPlot() {
        this.props.history.push('/');
    }

    render() {

        //user has directly entered /plot in address bar - redirect him / her back to home page
        if (!this.props.history.location.state) {
            return <Redirect to={{pathname: '/'}} />
        }

        const
            inputs = this.props.history.location.state,
            data = Object
                .values(inputs)
                .map((r: any) => r.selected),
            names = data.map(x => x ? x.name : undefined),
            resources = data.map(x => x ? x.url : undefined).filter(x => x);

        const {title, description} = generatePlot(...(names as [string, string, string?, string?, string?]));

        return (
            <div>
                <Container>
                    <Form>
                        <FormGroup>
                            <Title title={title} />
                            <Description description={description}/>
                            <Resources resources={resources} />
                            <GenerateNewPlotBnt generateNewPlot={this.generateNewPlot} />
                        </FormGroup>
                    </Form>
                </Container>
            </div>
        )
    }
}

export { Description, Title, ResourceLink, Resources, Plot };
