// version-G/src/components/pages/HomePage.vue
<template>
  <form v-if="isMandatoryDataLoaded()">
    <star-wars-search
      v-for="input in getVisibleInputs()"
      :key="input.name"
      :name="input.name"
      :label="input.label">
    </star-wars-search>
  </form>
  <div class="row" v-if="hasLoadingOfMandatoryDataFailed()">
    <div class="col-lg-12">
      <div class="alert alert-danger" role="alert">
        Loading of mandatory data failed, please try again later.
      </div>
    </div>
  </div>
  <div class="row" v-if="!isMandatoryDataLoaded() && !hasLoadingOfMandatoryDataFailed()">
    <div class="col-md-12">
      <h3>Please wait while star wars data is being loaded</h3>
      <div class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>
  </div>
</template>

<script>
import { defineComponent } from 'vue';
import { useStore } from 'vuex'
import { key } from "@/store/store";
import StarWarsSearch from "@/components/StarWarsSearch";

export default defineComponent({
  name: 'HomePage',
  components: {
    StarWarsSearch
  },
  setup() {
    const store = useStore(key);
    store.dispatch("loadMandatoryResources");

    function getVisibleInputs() {
      return store.getters.getVisibleInputs;
    }
    function isMandatoryDataLoaded() {
      return store.getters.isMandatoryDataLoaded;
    }
    function hasLoadingOfMandatoryDataFailed() {
      return store.getters.hasLoadingOfMandatoryDataFailed;
    }

    return {
      hasLoadingOfMandatoryDataFailed,
      isMandatoryDataLoaded,
      getVisibleInputs
    }
  }
})
</script>

<style scoped>
input {
  display: block;
  width: 100%;
}
.spinner-border {
  width: 5rem;
  height: 5rem;
}
</style>

// version-F/src/app/home/home-page/home-page.component.ts
import { Component } from '@angular/core';
import { AppStateService } from '../../services/app-state.service';
import { ResourceKey } from '../../services/types';

@Component({
  selector: 'app-home-page',
  templateUrl: './home-page.component.html',
  styleUrls: ['./home-page.component.css'],
})
export class HomePageComponent {

  appStateService: AppStateService;

  constructor(appStateService: AppStateService) {
    this.appStateService = appStateService;
  }

  ngOnInit() {
    this.appStateService.loadMandatoryData();
  }

  getInputs() {
    return this.appStateService.getVisibleInputs();
  }

  getOptionalInputs() {
    return this.appStateService.getOptionalInputs();
  }

  getOptionalButtonLabel(name: ResourceKey) {
    const visible = this.appStateService.isInputVisible(name);
    return visible ? `Remove ${name}` : `Add ${name}`;
  }

  loadData(name: ResourceKey) {
    this.appStateService.loadResourceData(name);
    this.appStateService.toggleVisibility(name);
  }

  isMandatoryDataLoaded() {
    return this.appStateService.isMandatoryDataLoaded();
  }

  areMandatoryFieldsSelected() {
    return this.appStateService.areMandatoryItemsSelected();
  }

  hasFailedLoadOfMandatoryData() {
    return this.appStateService.hasFailedLoadOfMandatoryData();
  }
}

<form *ngIf="isMandatoryDataLoaded()">
  <div class="form-group row" *ngFor="let input of getInputs()">
    <div class="col-md-12 text-left">
      <label class="col-form-label-lg" for="{{input.name}}">{{input.label | titlecase}}</label>
      <app-star-wars-search
        id="{{input.name}}"
        [label]="input.label"
        [resourceName]="input.name"
      >
      </app-star-wars-search>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-4" *ngFor="let input of getOptionalInputs()">
      <button
        type="button"
        class="btn btn-primary btn-lg"
        (click)="loadData(input.name)"
        [disabled]="!areMandatoryFieldsSelected()"
      >
        {{getOptionalButtonLabel(input.name)}}
      </button>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-12">
      <a routerLink="/plot">
        <button
          type="button"
          class="btn btn-primary btn-lg"
          [disabled]="!areMandatoryFieldsSelected()"
        >
          Generate
        </button>
      </a>
    </div>
  </div>
</form>
<div class="row" *ngIf="hasFailedLoadOfMandatoryData()">
  <div class="col-lg-12">
    <div class="alert alert-danger" role="alert">
      Loading of mandatory data failed, please try again later.
    </div>
  </div>
</div>
<div class="row" *ngIf="!isMandatoryDataLoaded() && !hasFailedLoadOfMandatoryData()">
  <div class="col-md-12">
    <h3>Please wait while star wars data is being loaded</h3>
    <div class="spinner-border" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </div>
</div>
