// version-G/src/components/OptionalInputs.vue
<template>
  <div class="form-group row">
    <div
      v-for="name in getOptionalNames()"
      :key="name"
      class="col-md-4" >
      <button
        type="button"
        class="btn btn-secondary btn-lg"
        v-bind:disabled="!areMandatoryInputSelected()"
      >
        {{getOptionalButtonLabel(name)}}
      </button>
    </div>
  </div>
</template>

<script>
import { defineComponent } from 'vue';
import { useStore } from "vuex";
import { key } from "@/store/store";

export default defineComponent({
  name: 'OptionalInputs',
  setup() {
    const store = useStore(key);

    function getOptionalNames() {
      return store.getters.getOptionalInputs.map(input => input.name);
    }
    function getOptionalButtonLabel(name) {
      const visible = store.getters.isInputVisible(name);
      return visible ? `Remove ${name}` : `Add ${name}`;
    }
    function areMandatoryInputSelected() {
      return store.getters.areMandatoryInputSelected;
    }

    return {
      getOptionalNames,
      getOptionalButtonLabel,
      areMandatoryInputSelected
    };
  }
});
</script>

<style scoped>
</style>

// version-B/src/pages/home/OptionalInputs.tsx
import React from 'react';
import {Button, Col} from "reactstrap";
import { OPTIONAL_RESOURCES } from '../../common/const';

const OPTIONAL_RESOURCES_SINGULAR: string[] = OPTIONAL_RESOURCES.map(r => r.singular);

type OptionalInputsProps = {
    visibles: boolean[],
    toggleVisibilityFn: (name: string) => void,
    disabled: boolean[]
};
const OptionalInputs: React.FC<OptionalInputsProps> = (props: OptionalInputsProps) => {
    const {visibles, toggleVisibilityFn, disabled} = props;
    return (
        <Col>
            <div className="row add-space button-row-space">
                { OPTIONAL_RESOURCES_SINGULAR.map(
                    (resource, idx) => <OptionalInputBnt
                        key={idx}
                        name={resource}
                        toggleVisibilityFn={toggleVisibilityFn}
                        visible={visibles[idx]}
                        disabled={disabled[idx]}
                    />
                )}
            </div>
        </Col>
    )
};

type OptionalInputBntProps = {
    name: string,
    toggleVisibilityFn: (name: string) => void,
    visible: boolean,
    disabled: boolean
};
const OptionalInputBnt: React.FC<OptionalInputBntProps> = (props: OptionalInputBntProps) => {
    const
        {name, toggleVisibilityFn, visible, disabled} = props,
        text = visible ? `Remove ${name}` : `Add ${name}`;
    return (
        <div className="col-sm-4">
            <div className="text-center">
                <Button
                    color="secondary"
                    size="lg"
                    onClick={e => toggleVisibilityFn(name)}
                    disabled={disabled}
                >
                    {text}
                </Button>
            </div>
        </div>
    );
};

export { OptionalInputs, OptionalInputBnt };
