// version-D/src/pages/home/LoadFailedAlerts.tsx
import React, {FC, useContext} from 'react';
import {Alert, Col} from 'reactstrap';

import { AppContext } from "../../AppContext";
import { AppState } from "../../common/types";

const LoadFailedAlerts: FC = () => {

    const
        context = useContext(AppContext),
        {failedLoadingOfOptionalData} = (context as AppState),
        failedOptional = failedLoadingOfOptionalData();

    return (
        <Col>
            <div className="row">
                {   failedOptional.map(
                        (name, idx) => <LoadFailedAlert key={idx} name={name}/>
                    )
                }
            </div>
        </Col>
    );
};

type LoadFailedAlertProps = { name: string };
const LoadFailedAlert: FC<LoadFailedAlertProps> = (props: LoadFailedAlertProps) => {
    return (
        <div className="text-center">
            <Alert color="danger">
                {`Loading of ${props.name} failed, please try again later.`}
            </Alert>
        </div>
    );
};

export { LoadFailedAlert, LoadFailedAlerts };

// version-G/src/components/LoadFailedAlerts.vue
<template>
  <div class="form-group row" v-if="getFailedOptionalResourceNames().length > 0">
    <div class="col-md-12" v-for="name in getFailedOptionalResourceNames()" :key="name">
      <div class="alert alert-danger" role="alert">
        Loading of {{name}} failed, please try again later.
      </div>
    </div>
  </div>
</template>

<script>
import { defineComponent } from 'vue';
import { useStore } from "vuex";
import { key } from "@/store/store";

export default defineComponent({
  name: 'LoadFailedAlerts',
  setup() {
    const store = useStore(key);

    function getFailedOptionalResourceNames() {
      return store.getters.getFailedOptionalInputNames;
    }

    return {
      getFailedOptionalResourceNames,
    };
  }
});

</script>

<style scoped>
</style>
