// version-G/src/components/LoadFailedAlerts.vue
<template>
  <div class="form-group row" v-if="getFailedOptionalResourceNames().length > 0">
    <div class="col-md-12" v-for="name in getFailedOptionalResourceNames()" :key="name">
      <div class="alert alert-danger" role="alert">
        Loading of {{name}} failed, please try again later.
      </div>
    </div>
  </div>
</template>

<script>
import { defineComponent } from 'vue';
import { useStore } from "vuex";
import { key } from "@/store/store";

export default defineComponent({
  name: 'LoadFailedAlerts',
  setup() {
    const store = useStore(key);

    function getFailedOptionalResourceNames() {
      return store.getters.getFailedOptionalInputNames;
    }

    return {
      getFailedOptionalResourceNames,
    };
  }
});

</script>

<style scoped>
</style>

// version-C/src/pages/home/LoadFailedAlerts.tsx
import React, { FC } from 'react';
import {Alert, Col} from 'reactstrap';
import {OPTIONAL_RESOURCES} from "../../common/const";

const OPTIONAL_RESOURCES_SINGULAR: string[] = OPTIONAL_RESOURCES.map(r => r.singular);

type LoadFailedAlertsProps = {
    visibles: boolean[]
};
const LoadFailedAlerts: FC<LoadFailedAlertsProps> = (props: LoadFailedAlertsProps) => {
    const {visibles} = props;
    return (
        <Col>
            <div className="row">
                { OPTIONAL_RESOURCES_SINGULAR.map(
                    (resource, idx) => <LoadFailedAlert
                        key={idx}
                        name={resource}
                        visible={visibles[idx]}
                    />
                )}
            </div>
        </Col>
    );
};

type LoadFailedAlertProps = {
    visible: boolean,
    name: string
};
const LoadFailedAlert: FC<LoadFailedAlertProps> = (props: LoadFailedAlertProps) => {
    const {name, visible} = props;
    if (visible) {
        return (
            <div className="text-center">
                <Alert color="danger">
                    {`Loading of ${name} failed, please try again later.`}
                </Alert>
            </div>
        );
    }
    return null;
};

export { LoadFailedAlert, LoadFailedAlerts };
